let allBlooks = {
Chick: "https://blooket.s3.us-east-2.amazonaws.com/blooks/farmAnimals/chick.svg",
Chicken: "https://blooket.s3.us-east-2.amazonaws.com/blooks/farmAnimals/chicken.svg",
Cow: "https://blooket.s3.us-east-2.amazonaws.com/blooks/farmAnimals/cow.svg",
Goat: "https://blooket.s3.us-east-2.amazonaws.com/blooks/farmAnimals/goat.svg",
Horse: "https://blooket.s3.us-east-2.amazonaws.com/blooks/farmAnimals/horse.svg",
Pig: "https://blooket.s3.us-east-2.amazonaws.com/blooks/farmAnimals/pig.svg",
Sheep: "https://blooket.s3.us-east-2.amazonaws.com/blooks/farmAnimals/sheep.svg",
Duck: "https://blooket.s3.us-east-2.amazonaws.com/blooks/farmAnimals/duck.svg",
Dog: "https://blooket.s3.us-east-2.amazonaws.com/blooks/pets/dog.svg",
Cat: "https://blooket.s3.us-east-2.amazonaws.com/blooks/pets/cat.svg",
Rabbit: "https://blooket.s3.us-east-2.amazonaws.com/blooks/pets/rabbit.svg",
Goldfish: "https://blooket.s3.us-east-2.amazonaws.com/blooks/pets/goldfish.svg",
Hamster: "https://blooket.s3.us-east-2.amazonaws.com/blooks/pets/hamster.svg",
Turtle: "https://blooket.s3.us-east-2.amazonaws.com/blooks/pets/turtle.svg",
Kitten: "https://blooket.s3.us-east-2.amazonaws.com/blooks/pets/kitten.svg",
Puppy: "https://blooket.s3.us-east-2.amazonaws.com/blooks/pets/puppy.svg",
Pumpkin: "https://blooket.s3.us-east-2.amazonaws.com/blooks/halloween/pumpkin.svg",
"Swamp Monster": "https://blooket.s3.us-east-2.amazonaws.com/blooks/halloween/swampMonster.svg",
Frankenstein: "https://blooket.s3.us-east-2.amazonaws.com/blooks/halloween/frankenstein.svg",
Vampire: "https://blooket.s3.us-east-2.amazonaws.com/blooks/halloween/vampire.svg",
Zombie: "https://blooket.s3.us-east-2.amazonaws.com/blooks/halloween/zombie.svg",
Mummy: "https://blooket.s3.us-east-2.amazonaws.com/blooks/halloween/mummy.svg",
Werewolf: "https://blooket.s3.us-east-2.amazonaws.com/blooks/halloween/werewolf.svg",
Ghost: "https://blooket.s3.us-east-2.amazonaws.com/blooks/halloween/ghost.svg",
Earth: "https://blooket.s3.us-east-2.amazonaws.com/blooks/space/earth.svg",
Meteor: "https://blooket.s3.us-east-2.amazonaws.com/blooks/space/meteor.svg",
Stars: "https://blooket.s3.us-east-2.amazonaws.com/blooks/space/stars.svg",
Alien: "https://blooket.s3.us-east-2.amazonaws.com/blooks/space/alien.svg",
Planet: "https://blooket.s3.us-east-2.amazonaws.com/blooks/space/planet.svg",
UFO: "https://blooket.s3.us-east-2.amazonaws.com/blooks/space/UFO.svg",
Spaceship: "https://blooket.s3.us-east-2.amazonaws.com/blooks/space/spaceship.svg",
Astronaut: "https://blooket.s3.us-east-2.amazonaws.com/blooks/space/astronaut.svg",
"Snowy Owl": "https://blooket.s3.us-east-2.amazonaws.com/blooks/arcticAnimals/snowyOwl.svg",
"Polar Bear": "https://blooket.s3.us-east-2.amazonaws.com/blooks/arcticAnimals/polarBear.svg",
"Arctic Fox": "https://blooket.s3.us-east-2.amazonaws.com/blooks/arcticAnimals/arcticFox.svg",
"Baby Penguin": "https://blooket.s3.us-east-2.amazonaws.com/blooks/arcticAnimals/babyPenguin.svg",
Penguin: "https://blooket.s3.us-east-2.amazonaws.com/blooks/arcticAnimals/penguin.svg",
"Arctic Hare": "https://blooket.s3.us-east-2.amazonaws.com/blooks/arcticAnimals/arcticHare.svg",
Seal: "https://blooket.s3.us-east-2.amazonaws.com/blooks/arcticAnimals/seal.svg",
Walrus: "https://blooket.s3.us-east-2.amazonaws.com/blooks/arcticAnimals/walrus.svg",
Bear: "https://blooket.s3.us-east-2.amazonaws.com/blooks/forestAnimals/bear.svg",
Moose: "https://blooket.s3.us-east-2.amazonaws.com/blooks/forestAnimals/moose.svg",
Fox: "https://blooket.s3.us-east-2.amazonaws.com/blooks/forestAnimals/fox.svg",
Raccoon: "https://blooket.s3.us-east-2.amazonaws.com/blooks/forestAnimals/raccoon.svg",
Squirrel: "https://blooket.s3.us-east-2.amazonaws.com/blooks/forestAnimals/squirrel.svg",
Owl: "https://blooket.s3.us-east-2.amazonaws.com/blooks/forestAnimals/owl.svg",
Hedgehog: "https://blooket.s3.us-east-2.amazonaws.com/blooks/forestAnimals/hedgehog.svg",
Pizza: "https://blooket.s3.us-east-2.amazonaws.com/blooks/foods/pizza.svg",
Sandwich: "https://blooket.s3.us-east-2.amazonaws.com/blooks/foods/sandwich.svg",
"Light Blue": "https://blooket.s3.us-east-2.amazonaws.com/blooks/colors/lightBlueBlook.svg",
Black: "https://blooket.s3.us-east-2.amazonaws.com/blooks/colors/blackBlook.svg",
Red: "https://blooket.s3.us-east-2.amazonaws.com/blooks/colors/redBlook.svg",
Purple: "https://blooket.s3.us-east-2.amazonaws.com/blooks/colors/purpleBlook.svg",
Pink: "https://blooket.s3.us-east-2.amazonaws.com/blooks/colors/pinkBlook.svg",
Orange: "https://blooket.s3.us-east-2.amazonaws.com/blooks/colors/orangeBlook.svg",
Lime: "https://blooket.s3.us-east-2.amazonaws.com/blooks/colors/limeBlook.svg",
Green: "https://blooket.s3.us-east-2.amazonaws.com/blooks/colors/greenBlook.svg",
Teal: "https://blooket.s3.us-east-2.amazonaws.com/blooks/colors/tealBlook.svg",
Tan: "https://blooket.s3.us-east-2.amazonaws.com/blooks/colors/tanBlook.svg",
Maroon: "https://blooket.s3.us-east-2.amazonaws.com/blooks/colors/maroonBlook.svg",
Gray: "https://blooket.s3.us-east-2.amazonaws.com/blooks/colors/grayBlook.svg",
Mint: "https://blooket.s3.us-east-2.amazonaws.com/blooks/colors/mintBlook.svg",
Salmon: "https://blooket.s3.us-east-2.amazonaws.com/blooks/colors/salmonColorBlook.svg",
Burgandy: "https://blooket.s3.us-east-2.amazonaws.com/blooks/colors/burgandyBlook.svg",
"Baby Blue": "https://blooket.s3.us-east-2.amazonaws.com/blooks/colors/babyBlueBlook.svg",
Dust: "https://blooket.s3.us-east-2.amazonaws.com/blooks/colors/dustBlook.svg",
Brown: "https://blooket.s3.us-east-2.amazonaws.com/blooks/colors/brownBlook.svg",
"Dull Blue": "https://blooket.s3.us-east-2.amazonaws.com/blooks/colors/dullBlueBlook.svg",
Yellow: "https://blooket.s3.us-east-2.amazonaws.com/blooks/colors/yellowBlook.svg",
Blue: "https://blooket.s3.us-east-2.amazonaws.com/blooks/colors/blueBlook.svg",
"Red Astronaut": "https://blooket.s3.us-east-2.amazonaws.com/blooks/bonus/space/redAstronaut.svg",
"Blue Astronaut": "https://blooket.s3.us-east-2.amazonaws.com/blooks/bonus/space/blueAstronaut.svg",
"Green Astronaut": "https://blooket.s3.us-east-2.amazonaws.com/blooks/bonus/space/greenAstronaut.svg",
"Pink Astronaut": "https://blooket.s3.us-east-2.amazonaws.com/blooks/bonus/space/pinkAstronaut.svg",
"Orange Astronaut": "https://blooket.s3.us-east-2.amazonaws.com/blooks/bonus/space/orangeAstronaut.svg",
"Yellow Astronaut": "https://blooket.s3.us-east-2.amazonaws.com/blooks/bonus/space/yellowAstronaut.svg",
"Black Astronaut": "https://blooket.s3.us-east-2.amazonaws.com/blooks/bonus/space/blackAstronaut.svg",
"Purple Astronaut": "https://blooket.s3.us-east-2.amazonaws.com/blooks/bonus/space/purpleAstronaut.svg",
"Brown Astronaut": "https://blooket.s3.us-east-2.amazonaws.com/blooks/bonus/space/brownAstronaut.svg",
"Cyan Astronaut": "https://blooket.s3.us-east-2.amazonaws.com/blooks/bonus/space/cyanAstronaut.svg",
"Lime Astronaut": "https://blooket.s3.us-east-2.amazonaws.com/blooks/bonus/space/limeAstronaut.svg",
"Rainbow Jellyfish": "https://blooket.s3.us-east-2.amazonaws.com/blooks/bonus/aquatic/rainbowJellyfish.svg",
"Blizzard Clownfish": "https://blooket.s3.us-east-2.amazonaws.com/blooks/bonus/aquatic/blizzardClownfish.svg",
"Lovely Frog": "https://blooket.s3.us-east-2.amazonaws.com/blooks/bonus/aquatic/lovelyFrog.svg",
"Lucky Frog": "https://blooket.s3.us-east-2.amazonaws.com/blooks/bonus/aquatic/luckyFrog.svg",
"Poison Dart Frog": "https://blooket.s3.us-east-2.amazonaws.com/blooks/bonus/aquatic/poisonDartFrog.svg",
"Lemon Crab": "https://blooket.s3.us-east-2.amazonaws.com/blooks/bonus/aquatic/lemonCrab.svg",
"Pirate Pufferfish": "https://blooket.s3.us-east-2.amazonaws.com/blooks/bonus/aquatic/piratePufferfish.svg",
"Donut Blobfish": "https://blooket.s3.us-east-2.amazonaws.com/blooks/bonus/aquatic/donutBlobfish.svg",
"Crimson Octopus": "https://blooket.s3.us-east-2.amazonaws.com/blooks/bonus/aquatic/crimsonOctopus.svg",
"Rainbow Narwhal": "https://blooket.s3.us-east-2.amazonaws.com/blooks/bonus/aquatic/rainbowNarwhal.svg",
"Haunted Pumpkin": "https://blooket.s3.us-east-2.amazonaws.com/blooks/bonus/halloween/hauntedPumpkin.svg",
"Spooky Pumpkin": "https://blooket.s3.us-east-2.amazonaws.com/blooks/bonus/halloween/spookyPumpkin.svg",
"Spooky Mummy": "https://blooket.s3.us-east-2.amazonaws.com/blooks/bonus/halloween/spookyMummy.svg",
"Frost Wreath": "https://blooket.s3.us-east-2.amazonaws.com/blooks/bonus/winterHoliday/frostWreath.svg",
"Tropical Globe": "https://blooket.s3.us-east-2.amazonaws.com/blooks/bonus/winterHoliday/tropicalGlobe.svg",
"White Peacock": "https://blooket.s3.us-east-2.amazonaws.com/blooks/bonus/safari/whitePeacock.svg",
"Tiger Zebra": "https://blooket.s3.us-east-2.amazonaws.com/blooks/bonus/safari/tigerZebra.svg",
"Agent Owl": "https://blooket.s3.us-east-2.amazonaws.com/blooks/bonus/td/agentOwl.svg",
"Master Elf": "https://blooket.s3.us-east-2.amazonaws.com/blooks/bonus/td/masterElf.svg",
"Spooky Ghost": "https://blooket.s3.us-east-2.amazonaws.com/blooks/bonus/halloween/spookyGhost.svg",
"Tim the Alien": "https://blooket.s3.us-east-2.amazonaws.com/blooks/bonus/space/timTheAlien.svg",
"Phantom King": "https://blooket.s3.us-east-2.amazonaws.com/blooks/bonus/td/phantomKing.svg",
"Rainbow Astronaut": "https://blooket.s3.us-east-2.amazonaws.com/blooks/bonus/space/purpleAstronaut.svg",
Tiger: "https://blooket.s3.us-east-2.amazonaws.com/blooks/tropicalAnimals/tiger.svg",
Orangutan: "https://blooket.s3.us-east-2.amazonaws.com/blooks/tropicalAnimals/orangutan.svg",
Cockatoo: "https://blooket.s3.us-east-2.amazonaws.com/blooks/tropicalAnimals/cockatoo.svg",
Parrot: "https://blooket.s3.us-east-2.amazonaws.com/blooks/tropicalAnimals/parrot.svg",
Anaconda: "https://blooket.s3.us-east-2.amazonaws.com/blooks/tropicalAnimals/anaconda.svg",
Jaguar: "https://blooket.s3.us-east-2.amazonaws.com/blooks/tropicalAnimals/jaguar.svg",
Macaw: "https://blooket.s3.us-east-2.amazonaws.com/blooks/tropicalAnimals/macaw.svg",
Toucan: "https://blooket.s3.us-east-2.amazonaws.com/blooks/tropicalAnimals/toucan.svg",
Panther: "https://blooket.s3.us-east-2.amazonaws.com/blooks/tropicalAnimals/panther.svg",
Capuchin: "https://blooket.s3.us-east-2.amazonaws.com/blooks/tropicalAnimals/capuchin.svg",
Panda: "https://blooket.s3.us-east-2.amazonaws.com/blooks/safari/panda.svg",
Sloth: "https://blooket.s3.us-east-2.amazonaws.com/blooks/safari/sloth.svg",
Tenrec: "https://blooket.s3.us-east-2.amazonaws.com/blooks/safari/tenrec.svg",
Flamingo: "https://blooket.s3.us-east-2.amazonaws.com/blooks/safari/flamingo.svg",
Zebra: "https://blooket.s3.us-east-2.amazonaws.com/blooks/safari/zebra.svg",
Elephant: "https://blooket.s3.us-east-2.amazonaws.com/blooks/safari/elephant.svg",
Lemur: "https://blooket.s3.us-east-2.amazonaws.com/blooks/safari/lemur.svg",
Peacock: "https://blooket.s3.us-east-2.amazonaws.com/blooks/safari/peacock.svg",
Chameleon: "https://blooket.s3.us-east-2.amazonaws.com/blooks/safari/chameleon.svg",
Lion: "https://blooket.s3.us-east-2.amazonaws.com/blooks/safari/lion.svg",
"Rainbow Panda": "https://blooket.s3.us-east-2.amazonaws.com/blooks/safari/rainbowPanda.svg",
"Lil Bot": "https://blooket.s3.us-east-2.amazonaws.com/blooks/bots/lilBot.svg",
"Lovely Bot": "https://blooket.s3.us-east-2.amazonaws.com/blooks/bots/lovelyBot.svg",
"Angry Bot": "https://blooket.s3.us-east-2.amazonaws.com/blooks/bots/angryBot.svg",
"Happy Bot": "https://blooket.s3.us-east-2.amazonaws.com/blooks/bots/happyBot.svg",
Watson: "https://blooket.s3.us-east-2.amazonaws.com/blooks/bots/watson.svg",
"Buddy Bot": "https://blooket.s3.us-east-2.amazonaws.com/blooks/bots/buddyBot.svg",
"Brainy Bot": "https://blooket.s3.us-east-2.amazonaws.com/blooks/bots/brainyBot.svg",
"Mega Bot": "https://blooket.s3.us-east-2.amazonaws.com/blooks/bots/megaBot.svg",
"Old Boot": "https://blooket.s3.us-east-2.amazonaws.com/blooks/aquatic/oldBoot.svg",
Jellyfish: "https://blooket.s3.us-east-2.amazonaws.com/blooks/aquatic/jellyfish.svg",
Clownfish: "https://blooket.s3.us-east-2.amazonaws.com/blooks/aquatic/clownfish.svg",
Frog: "https://blooket.s3.us-east-2.amazonaws.com/blooks/aquatic/frog.svg",
Crab: "https://blooket.s3.us-east-2.amazonaws.com/blooks/aquatic/crab.svg",
Pufferfish: "https://blooket.s3.us-east-2.amazonaws.com/blooks/aquatic/pufferFish.svg",
Blobfish: "https://blooket.s3.us-east-2.amazonaws.com/blooks/aquatic/blobfish.svg",
Octopus: "https://blooket.s3.us-east-2.amazonaws.com/blooks/aquatic/octopus.svg",
Narwhal: "https://blooket.s3.us-east-2.amazonaws.com/blooks/aquatic/narwhal.svg",
"Baby Shark": "https://blooket.s3.us-east-2.amazonaws.com/blooks/aquatic/babyShark.svg",
Megalodon: "https://blooket.s3.us-east-2.amazonaws.com/blooks/aquatic/megalodon.svg",
Toast: "https://blooket.s3.us-east-2.amazonaws.com/blooks/breakfast/toast.svg",
Cereal: "https://blooket.s3.us-east-2.amazonaws.com/blooks/breakfast/cereal.svg",
Yogurt: "https://blooket.s3.us-east-2.amazonaws.com/blooks/breakfast/yogurt.svg",
"Breakfast Combo": "https://blooket.s3.us-east-2.amazonaws.com/blooks/breakfast/breakfastCombo.svg",
"Orange Juice": "https://blooket.s3.us-east-2.amazonaws.com/blooks/breakfast/orangeJuice.svg",
Milk: "https://blooket.s3.us-east-2.amazonaws.com/blooks/breakfast/milk.svg",
Waffle: "https://blooket.s3.us-east-2.amazonaws.com/blooks/breakfast/waffle.svg",
Pancakes: "https://blooket.s3.us-east-2.amazonaws.com/blooks/breakfast/pancakes.svg",
"French Toast": "https://blooket.s3.us-east-2.amazonaws.com/blooks/breakfast/frenchToast.svg",
Witch: "https://blooket.s3.us-east-2.amazonaws.com/blooks/medieval/witch.svg",
Wizard: "https://blooket.s3.us-east-2.amazonaws.com/blooks/medieval/wizard.svg",
Elf: "https://blooket.s3.us-east-2.amazonaws.com/blooks/medieval/elf.svg",
Fairy: "https://blooket.s3.us-east-2.amazonaws.com/blooks/medieval/fairy.svg",
"Slime Monster": "https://blooket.s3.us-east-2.amazonaws.com/blooks/medieval/slimeMonster.svg",
Jester: "https://blooket.s3.us-east-2.amazonaws.com/blooks/medieval/jester.svg",
Dragon: "https://blooket.s3.us-east-2.amazonaws.com/blooks/medieval/dragon.svg",
Queen: "https://blooket.s3.us-east-2.amazonaws.com/blooks/medieval/queen.svg",
Unicorn: "https://blooket.s3.us-east-2.amazonaws.com/blooks/medieval/unicorn.svg",
King: "https://blooket.s3.us-east-2.amazonaws.com/blooks/medieval/king.svg",
"Snow Globe": "https://blooket.s3.us-east-2.amazonaws.com/blooks/winterHoliday/snowGlobe.svg",
"Holiday Gift": "https://blooket.s3.us-east-2.amazonaws.com/blooks/winterHoliday/holidayGift.svg",
"Hot Chocolate": "https://blooket.s3.us-east-2.amazonaws.com/blooks/winterHoliday/hotChocolate.svg",
"Holiday Wreath": "https://blooket.s3.us-east-2.amazonaws.com/blooks/winterHoliday/holidayWreath.svg",
"Gingerbread Man": "https://blooket.s3.us-east-2.amazonaws.com/blooks/winterHoliday/gingerbreadMan.svg",
"Gingerbread House": "https://blooket.s3.us-east-2.amazonaws.com/blooks/winterHoliday/gingerbreadHouse.svg",
Snowman: "https://blooket.s3.us-east-2.amazonaws.com/blooks/winterHoliday/snowman.svg",
"Santa Claus": "https://blooket.s3.us-east-2.amazonaws.com/blooks/winterHoliday/santaClaus.svg",
"Two of Spades": "https://blooket.s3.us-east-2.amazonaws.com/blooks/wonderland/twoOfSpades.svg",
"Eat Me": "https://blooket.s3.us-east-2.amazonaws.com/blooks/wonderland/eat.svg",
"Drink Me": "https://blooket.s3.us-east-2.amazonaws.com/blooks/wonderland/drink.svg",
Alice: "https://blooket.s3.us-east-2.amazonaws.com/blooks/wonderland/alice.svg",
"Queen of Hearts": "https://blooket.s3.us-east-2.amazonaws.com/blooks/wonderland/queenOfHearts.svg",
Dormouse: "https://blooket.s3.us-east-2.amazonaws.com/blooks/wonderland/dormouse.svg",
"White Rabbit": "https://blooket.s3.us-east-2.amazonaws.com/blooks/wonderland/whiteRabbit.svg",
"Cheshire Cat": "https://blooket.s3.us-east-2.amazonaws.com/blooks/wonderland/cheshireCat.svg",
Caterpillar: "https://blooket.s3.us-east-2.amazonaws.com/blooks/wonderland/caterpillar.svg",
"Mad Hatter": "https://blooket.s3.us-east-2.amazonaws.com/blooks/wonderland/madHatter.svg",
"King of Hearts": "https://blooket.s3.us-east-2.amazonaws.com/blooks/wonderland/kingOfHearts.svg"
};
export {allBlooks};
